name: Birthday Bot

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify the Node.js version you are using

    # Step to restore the WhatsApp auth cache
    - name: Restore WhatsApp auth cache
      uses: actions/cache@v3
      with:
        path: |
          .wwebjs_auth   # Restore the authentication cache
        key: whatsapp-auth-${{ github.sha }}  # Cache key for .wwebjs_auth
        restore-keys: |
          whatsapp-auth-

    # Step to restore the WhatsApp session cache
    - name: Restore WhatsApp session cache
      uses: actions/cache@v3
      with:
        path: |
          .wwebjs_cache  # Restore the session cache
        key: whatsapp-session-${{ github.sha }}  # Cache key for .wwebjs_cache
        restore-keys: |
          whatsapp-session-

    - name: Install dependencies
      run: npm install

    - name: Run the bot
      run: node bot.js
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
        ADMIN_NUMBER: ${{ secrets.ADMIN_NUMBER }}

    # Step to save the WhatsApp auth cache after the run
    - name: Save WhatsApp auth cache
      uses: actions/cache@v3
      with:
        path: |
          .wwebjs_auth   # Save the authentication cache
        key: whatsapp-auth-${{ github.run_id }}  # Unique cache key for .wwebjs_auth

    # Step to save the WhatsApp session cache after the run
    - name: Save WhatsApp session cache
      uses: actions/cache@v3
      with:
        path: |
          .wwebjs_cache  # Save the session cache
        key: whatsapp-session-${{ github.run_id }}  # Unique cache key for .wwebjs_cache
